### ISSUE TITLE
Does this not work on Ubuntu 18?

### ISSUE THREAD

**Issue by PickleJr** [altdesktop/i3ipc-glib#20]
Pretty much title. I was trying to install i3 gaps on ubuntu and when running `sudo add-apt-repository ppa:aacebedo/libi3ipc-glib` I get a 404 error.

**Comment by cornerman** [comment]
It should work on ubuntu 18, but the package maintainer seems to have not yet (?) released this ppa for 18.04. Maybe you can contact the package maintainer and ask him whether he will upload a package for the new ubuntu version?

**Comment by PickleJr** [comment]
Thanks for the feedback! Do you know who the package manager is? Is It the owner of this repo?

**Comment by aacebedo** [comment]
I've added the bionic and cosmic build to launchpad. 
Let's see if it is still building...

**Comment by acrisci** [comment]
Let me know if you have problems and tag me on issues if you do. I'm still around just working on other things.
