### ISSUE TITLE
The default example is not compiling, (i3ipc-glib is not in pkg-config)...

### ISSUE THREAD

**Issue by RoboCopGay** [altdesktop/i3ipc-glib#28]
The `README.md` recommends that I compile with `gcc $(pkg-config --libs --cflags i3ipc-glib-1.0) <file.c> -o <binary>`, but i3ipc-glib is not in `pkg-config`

```sh
$ pkg-config --libs --cflags i3ipc-glib-1.0
Package i3ipc-glib-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `i3ipc-glib-1.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'i3ipc-glib-1.0', required by 'virtual:world', not found

```

What i need to do?

**Comment by acrisci** [comment]
> Perhaps you should add the directory containing `i3ipc-glib-1.0.pc' to the PKG_CONFIG_PATH environment variable

```
PKG_CONFIG_PATH=/path/to/i3ipc-glib-1.0.pc
```

It should be in the build directory somewhere. I recommend actually installing somewhere, maybe in your home directory.

**Comment by RoboCopGay** [comment]
thanks!! it is working now.
