### ISSUE TITLE
Error while running autogen.sh

### ISSUE THREAD

**Issue by gary-lgy** [altdesktop/i3ipc-glib#30]
I followed the instructions in the README to build the package. While running `./autogen.sh`, I encountered this error:
![image](https://user-images.githubusercontent.com/44059321/71370304-86a7b680-25e8-11ea-9c8c-8068109a6084.png)
I'm not familiar with the build tools, but it seems that the `./build/autotools` directory was removed in the latest commit. Could that be the reason?

**Comment by acrisci** [comment]
Oh yeah I didn't notice that. That should be fixed.

**Comment by DaitiDay** [comment]
I still experience the same issue
