### ISSUE TITLE
How to register `user_function` to signal?

### ISSUE THREAD

**Issue by LRDPRDX** [altdesktop/i3ipc-glib#33]
I want to know how do I exactly map my function (`user_function` in the documentation) to signal. Does this action assume a user has knowledge of `glib` itself? Provided the following code:
```
#define THIS_SOCKET_PATH "/run/user/1000/i3/ipc-socket.1438"

void print_change( i3ipcConnection *self, i3ipcWindowEvent *e, gpointer user_data )
{
    printf( "Change : %s\n", e->change );
}

int main()
{
    i3ipcConnection *conn;
   
    conn = i3ipc_connection_new(THIS_SOCKET_PATH, NULL);
    //subscribe to window event
    i3ipcCommandReply *cr = i3ipc_connection_subscribe( conn, I3IPC_EVENT_WINDOW, NULL );
    //check the reply
    g_printf( "Subscription:%d\n", cr->success );

    //How do I register my function `print_change? The below won't compile obviously
    //i3ipc_connection_on( conn, "window", &print_change, NULL );
    //wait for events
    i3ipc_connection_main( conn );

    g_object_unref(conn);

    return 0;
}
```
How do I register `print_change` in order it is called whenever a window event happens?

**Comment by acrisci** [comment]
Yeah I don't really like `i3ipc_connection_on()`.

Use this:

https://developer.gnome.org/gobject/stable/gobject-The-Base-Object-Type.html#g-object-connect

Examples are definitely needed to show how this works.

**Comment by LRDPRDX** [comment]
Yes, examples are needed (:

**Comment by acrisci** [comment]
https://github.com/altdesktop/i3ipc-glib/tree/master/examples
